fmt:
	clang-format -i `find src -name '*.cpp'`
	clang-format -i `find src -name '*.hpp'`

clean:
	cd src/build && rm -rf *

bpy:
	python3 build.py

build:
	g++ src/main.cpp -o build/RayTracing -O3 -march=native -std=c++20  -Wall -Wextra

debug:
	g++ src/main.cpp -o build/RayTracing -O3 -march=native -std=c++20

move:
	mv *.bmp images/

run:
	./build/RayTracing
