fmt:
	clang-format -i `find . -name '*.cpp' -not -path '*/*build*/*'`
	clang-format -i `find . -name '*.hpp' -not -path '*/*build*/*'`

clean:
	cd code/build && rm -rf *

build:
	python3 build.py

move:
	mv *.bmp images/